apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-276910
  artifacts:
    # - image: kikomega/auth
    - image: us.gcr.io/ticketing-dev-276910/auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: kikomega/client
    - image: us.gcr.io/ticketing-dev-276910/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    # - image: kikomega/tickets
    - image: us.gcr.io/ticketing-dev-276910/tickets
      context: tickets
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
